# Generated by Django 3.2.4 on 2021-07-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('Author', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1000)),
                ('image', models.ImageField(default='articles/default.jpg', upload_to='articles')),
                ('source', models.URLField(max_length=225)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
