# Generated by Django 3.2.4 on 2021-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_author_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1000)),
                ('image', models.ImageField(default='articles/default.jpg', upload_to='articles')),
                ('source', models.URLField(max_length=225)),
            ],
            options={
                'verbose_name': 'UserArticle',
                'verbose_name_plural': 'UserArticles',
            },
        ),
    ]
