# Generated by Django 3.2.4 on 2021-07-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_userarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarticle',
            name='image',
            field=models.ImageField(upload_to='articles'),
        ),
    ]
