# Generated by Django 3.2.4 on 2021-08-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarticle',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
