# Generated by Django 3.2.4 on 2021-08-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_userarticle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userarticle',
            name='content',
            field=models.TextField(),
        ),
    ]
